//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighlightStore
    {
        public decimal ID { get; set; }
        public string IMAGE_COVER { get; set; }
        public string IMAGE_LOGO { get; set; }
        public string TITLE { get; set; }
        public string SUBTITLE { get; set; }
        public string EMAIL { get; set; }
        public string WORK_HOUR { get; set; }
        public string INSTAGRAM { get; set; }
        public string FACEBOOK { get; set; }
        public string YOUTUBE { get; set; }
        public string WEBSITE { get; set; }
        public string TOKOPEDIA { get; set; }
        public string DEKORUMA { get; set; }
        public System.DateTime CREATED_AT { get; set; }
        public System.DateTime UPDATED_AT { get; set; }
    }
}
