//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Katalogue
    {
        public decimal ID { get; set; }
        public string TITLE { get; set; }
        public string SUBTITLE { get; set; }
        public string PDF_URL { get; set; }
        public string IMAGE_URL { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public System.DateTime UPDATED_AT { get; set; }
    }
}
